ros_release: 'hydro'
ros_user: 'ronexserial'
ros_user_comment: 'RoNeX Program And Test'
ros_user_password: "password"
ros_user_email: 'software@shadowrobot.com'
ros_user_background: "files/images/ronex.jpg"
monospace_font: "Ubuntu Mono 11"
ros_packages:
  - sr-ronex
shadow_opt: /opt/shadow
ronexserial_installdir: "{{ shadow_opt }}/sr-ronex-serial-db"
ronexserial_repo: git@github.com:shadow-robot/sr-ronex-serial-db
ronexserial_dbname: ronexserial
ronexserial_dbuser: ronexserial
ronexserial_dbpassword: password
ronexserial_dbhost: localhost
ronexserial_dbport: 5432
shared_folder: "{{ronexserial_installdir}}"

