---
# Playbook for additional component installations


- name: Removing lock
  shell: rm "/var/lib/dpkg/lock"
  sudo: yes

- name: Install more packages
  apt: name={{item}}
  sudo: yes
  sudo_user: "{{ros_user}}"
  with_items:
     - ros-{{ros_release}}-cmake-modules
     - python-rosdep
     - python-pip
     - cobertura
     - python-bloom
     - fakeroot

- name: Install PIP modules
  pip: name={{item}} extra_args='--upgrade'
  sudo: yes
  with_items:
     - catkin_pkg
     - empy
     - coverage

- name: Update users bashrc to point to the ROS installation
  lineinfile: dest={{ansible_env.HOME}}/.bashrc
              line="source /opt/ros/{{ros_release}}/setup.bash"
              regexp='^source.*/setup\.bash'
              insertafter=EOF
              backup=yes


