---
- name: Add KCL remote
  sudo: yes
  sudo_user: "{{ ros_user }}"
  command: git remote add kcl git@github.com:shadow-robot/kcl-gsc-source-code.git
           chdir={{ ros_workspace }}/src/sr_grasp_stabilisation
