---
# PyCharm IDE installation

- name: Update package lists
  apt: update_cache=yes
  become: yes
  become_method: sudo
  become_user: root

- name: Intall needed libs
  apt: name={{item}} install_recommends=no
  become: yes
  become_method: sudo
  become_user: root
  with_items:
    - wget
    - git
    - default-jre
    - libxrender1
    - libxtst6
    - python

- name: Install PyCharm
  script: ../files/install_pycharm.sh {{pycharm_home}}
  become: yes
  become_method: sudo
  become_user: root
