---
# Playbook for Shadow Debian repository

- name: check if x509_path variable was set
  fail: msg="Variable x509_path was not set"
  when: x509_path is not defined

- name: Update package lists
  apt: update_cache=yes

- name: Install HTTPS transport for apt
  apt: name=apt-transport-https

- name: Create apt ssl directory
  file: path=/etc/apt/ssl/ state=directory

- name: Copy client certificate and GPG key for Shadow repo access
  copy: src={{x509_path}}/{{item}} dest=/etc/apt/ssl/{{item}} force=yes
  with_items:
    - shadow_ca.crt
    - shadow_cert.crt
    - shadow_client.key

- name: Copy Shadow https settings for apt
  copy: src=../files/00https dest=/etc/apt/apt.conf.d/00https force=yes

- name: Add Shadow repo key
  apt_key: id=27A0924ADA2A1511 url=https://packages.shadowrobot.com/shadow.gpg.key state=present validate_certs=no

- name: Adding Shadow PPA
  apt_repository: repo='deb [arch=amd64] https://packages.shadowrobot.com/general {{ubuntu_version_name}} main' state=present mode=644 filename='shadow-packages'

- name: Update package lists
  apt: update_cache=yes

- name: Create rosdep directory
  file: path=/etc/ros/rosdep/sources.list.d/ state=directory

- name: Registering Shadow rosdep rule
  template: src=11-shadow.list dest=/etc/ros/rosdep/sources.list.d/11-shadow.list force=yes
