---
# Playbook for python code coverage

- name: Set CATKIN_TEST_COVERAGE to True
  set_fact:
    python_code_coverage_options: "CATKIN_TEST_COVERAGE=1"

- name: Install PIP coverage module
  pip: name={{item}} extra_args='--upgrade'
  with_items:
     - coverage

- name: Creates the coverage repository
  file: path={{ros_workspace}}/coverage state=directory

- name: Make sure it's empty (previous builds)
  shell: rm -rf {{ros_workspace}}/coverage/*
