---
# Playbook for python code coverage

- name: Set CATKIN_TEST_COVERAGE to True
  environment:
    CATKIN_TEST_COVERAGE: 1

- name: Creates the coverage repository
  file: path={{ros_workspace}}/coverage state=directory

- name: Make sure it's empty (previous builds)
  shell: rm -rf {{ros_workspace}}/coverage/*
