---
# Playbook for Semaphore CI specific code

- name: check if test_results_dir variable was set by build server
  fail: msg="Variable test_results_dir was not set by CI server"
  when: test_results_dir is not defined

- name: check if code_coverage_results_dir variable was set by build server
  fail: msg="Variable code_coverage_results_dir was not set by CI server"
  when: code_coverage_results_dir is not defined

- name: Move unit tests results
  shell: bash -c "ls {{ros_workspace}}/build/test_results/* >/dev/null 2>&1 && mv -vt {{test_results_dir}} {{ros_workspace}}/build/test_results/*"
  ignore_errors: yes

- name: Fail in case if unit tests failing
  shell: bash -c "! grep -R '<failure' {{test_results_dir}}"
