---
- name: Create /opt/shadow workspace dir
  file: state=directory path=/opt/shadow owner={{ros_user}} group=ros

- name: Fix perms
  file: path=/opt/shadow recurse=yes owner={{ros_user}} group=ros

- name: Checkout the ronex serial db repository
  git: repo=git@github.com:shadow-robot/sr-ronex-serial-db dest="/opt/shadow/sr-ronex-serial-db" accept_hostkey=True
  sudo: yes

- name: Fix perms
  file: path=/opt/shadow recurse=yes owner={{ros_user}} group=ros

- name: Build SOEM
  shell: bash -c "source /opt/shadow/sr-ronex-serial-db/SOEM1.3.0/setup.sh linux && make all"
    chdir="/opt/shadow/sr-ronex-serial-db/SOEM1.3.0"
  sudo: yes
  sudo_user: "{{ros_user}}"

- name: Install packages
  apt: name={{item}}
  with_items:
    - python-pip
    - ccze
    - sqlite3

- name: Install Django 1.5
  shell: pip install Django==1.5

- name: Add local database settings for easy setup
  shell: cp /opt/shadow/sr-ronex-serial-db/ronexserial/ronexserial/dbsettings.py.local  /opt/shadow/sr-ronex-serial-db/ronexserial/ronexserial/dbsettings.py
  sudo: yes
  sudo_user: "{{ros_user}}"

- name: Create ~{{ros_user}}/logs dir
  file: state=directory path=~{{ros_user}}/logs owner={{ros_user}} group=ros

- name: Setup soem for normal user
  shell: "setcap cap_sys_nice,cap_ipc_lock,cap_net_raw,cap_net_admin=eip /opt/shadow/sr-ronex-serial-db/ronexserial/bin/eepromtool"

- name: Create autostart directory
  file: state=directory path="~{{ros_user}}/.config/autostart" owner={{ros_user}} group=ros

- name: Start server at login
  file: state=link
    src="~{{ros_user}}/Desktop/FlashRonex.desktop"
    dest="~{{ros_user}}/.config/autostart/FlashRonex.desktop"
    force=yes

- name: Start webui at login
  file: state=link
    src="~{{ros_user}}/Desktop/FlashRonexWebUi.desktop"
    dest="~{{ros_user}}/.config/autostart/FlashRonexWebUi.desktop"
    force=yes
