# Set up the mongodb database

- name: Clone mongo-cxx-driver in {{workspace_path}}
  sudo: yes
  git:
    repo: 'https://github.com/mongodb/mongo-cxx-driver.git'
    version: 26compat
    dest: "{{workspace_path}}/src/mongo-cxx-driver"
    clone: yes
    update: yes

- name: Install scons package
  sudo: yes
  apt:
    name: scons

- name: Install mongodb package
  sudo: yes
  apt:
    name: mongodb

- name: Build mongodb from source
  sudo: yes
  shell: scons --use-system-boost --prefix=/usr/local/ --full --disable-warnings-as-errors
    chdir: "{{workspace_path}}/src/mongo-cxx-driver"

- name: Download warehouse_ros_mongo source
  sudo: yes
  shell: bash -c 'wstool set -yu warehouse_ros_mongo --git https://github.com/ros-planning/warehouse_ros_mongo.git -v jade-devel'
    chdir: "{{workspace_path}}/src"
    
- name: Download warehouse_ros source
  sudo: yes
  shell: bash -c 'wstool set -yu warehouse_ros --git https://github.com/ros-planning/warehouse_ros.git -v jade-devel'
    chdir: "{{workspace_path}}/src"

- name: Changing folders owner
  sudo: yes
  shell: bash -c "chown -R {{ros_user}}:{{ros_user}} mongo-cxx-driver warehouse_ros"
    chdir: "{{workspace_path}}/src"

- name: Build the workspace
  sudo: yes
  shell: bash -c "source /opt/ros/kinetic/setup.bash && catkin_make"
    chdir: "{{workspace_path}}"
