---
# Playbook for C++ code style check

- name: check if project_sources_path variable was set
  fail: msg="Variable project_sources_path was not set"
  when: project_sources_path is not defined

- name: Read all packages paths in project
  shell: find -type f -name package.xml -printf "%h\n" chdir={{project_sources_path}}
  register: package_paths_list

- name: Find C++ files in each package
  shell: find -type f \( -name "*.h" -o -name "*.cpp" \) -printf "%p "
    chdir={{project_sources_path}}/{{item}}
  with_items: "{{package_paths_list.stdout_lines|list}}"
  register: package_paths_and_cpp_files

- name: Execute roslint for every package and write results in unit tests format
  shell: bash -c "source /opt/ros/{{ros_release}}/setup.bash && rosrun roslint test_wrapper {{ros_workspace}}/build/test_results/{{item.item|basename}}/roslint-cpp-{{item.item|basename}}.xml 'rosrun roslint cpplint {{item.stdout}}' "
    chdir={{project_sources_path}}/{{item.item}}
  with_items: "{{package_paths_and_cpp_files.results|list}}"
  when: item.stdout != ""
  ignore_errors: True
