---
# Playbook for C++ code style check

- name: Find C++ h and cpp files in each package
  shell: find -type f \( -name "*.h" -o -name "*.cpp" -o -name "*.hpp" \) -printf "%p "
    chdir={{repo_sources_path}}/{{item.path}}
  with_items: "{{repo_packages_list|default([])}}"
  register: repo_packages_and_h_cpp_files

- name: Set variable to workaround ansible type evaluation issue
  set_fact:
    repo_packages_and_h_cpp_files_results: "{{repo_packages_and_h_cpp_files.results}}"

- name: Execute roslint for every package and write results in unit tests format
  shell: bash -c "source /opt/ros/{{ros_release}}/setup.bash && mkdir -p \"{{lint_result_dir}}/{{item.item.name}}\" && rosrun roslint cpplint --extensions=hpp,cpp,h --filter=-runtime/references {{item.stdout}} &> \"{{lint_result_dir}}/{{item.item.name}}/roslint-h-cpp-{{item.item.name}}.cpplint\""
    chdir={{repo_sources_path}}/{{item.item.path}}
  with_items: "{{repo_packages_and_h_cpp_files_results|default([])}}"
  when: item.stdout != ""
  ignore_errors: True
