---
# Finalising the python code coverage tasks (combining files and exporting to xml)

- name: Find all .coverage files in {{ros_workspace}}
  shell: find `pwd` -type f -name .coverage -printf "%p " chdir={{ros_workspace}}/build/{{item.name}}
  with_items: "{{repo_packages_list|default([])}}"
  register: coverage_paths_list

- name: Make coverage folder for each package that has coverage information
  file: state=directory path={{code_coverage_results_dir}}/{{item.item.name}}
  with_items: "{{ coverage_paths_list.results }}"

- name: Combine the coverage files
  shell: bash -c 'coverage combine {{item.stdout}}' chdir={{code_coverage_results_dir}}/{{item.item.name}}
  with_items: "{{ coverage_paths_list.results }}"

- name: Touch .coveragerc for all repos, creating it if necessary
  shell: touch "{{repo_sources_path}}/{{item.path}}/.coveragerc"
  with_items: "{{repo_packages_list|default([])}}"

- name: Move .coveragerc files to coverage data folder
  shell: cp "{{repo_sources_path}}/{{item.path}}/.coveragerc" {{item.name}} chdir={{code_coverage_results_dir}}
  with_items: "{{repo_packages_list|default([])}}"

- name: Generate xml coverage report
  shell: coverage xml -o coverage.python.xml --rcfile=.coveragerc chdir={{code_coverage_results_dir}}/{{item.item.name}}
  with_items: "{{ coverage_paths_list.results }}"

- name: Replace paths in coverage report to be relative
  shell: sed -i "s_/home/user/workspace/src/host/workspace_`python -c 'import os.path; print os.path.relpath(\'/home/user/workspace/src/host/workspace\', \'{{code_coverage_results_dir}}/{{item.item.name}}\')'`_g" "{{item.name}}/coverage.python.xml" && sed -i "s_\.home\.user\.workspace\.src\.host\.workspace\.__g" "coverage.python.xml" chdir={{code_coverage_results_dir}}/{{item.item.name}}
  with_items: "{{ coverage_paths_list.results }}"
