---
# Playbook for copy source code from repository to Docker image

- name: Remove source directory in case of caching
  shell: bash -c "rm -rf {{repo_sources_path}}"

- name: Create directory again
  file: state=directory path={{repo_sources_path}}

- name: Copy source directory from host machine
  shell: bash -c "shopt -s dotglob && cp -r {{server_repo_dir}}/* {{repo_sources_path}}"
