---
# Playbook for uploading deb files to an apt repo

- name: List all present deb packages
  shell: bash -c "ls *.deb"
    chdir={{repo_sources_path}}

- name: Send files to aptly repository
  shell: curl -X POST -F file=@ros-indigo-sr-benchmarking_0.0.0-0trusty_amd64.deb http://10.10.10.62:8080/api/files/ros-indigo-sr-benchmarking
    chdir={{repo_sources_path}}
