---
# Playbook for uploading deb files to an apt repo

- name: List all present deb packages
  shell: bash -c "ls *.deb"
    chdir={{repo_sources_path}}

- name: Send files to aptly repository
  shell: curl -X POST -F file=@{{item}} http://10.10.10.62:8080/api/files/{{item}}
    chdir={{repo_sources_path}}
  with_fileglob:
    - {{repo_sources_path}}/*.deb
