---
# Playbook for uploading deb files to an apt repo

- name: List all present deb packages
  shell: bash -c "ls *.deb"
    chdir={{repo_sources_path}}

- name: Save deb paths
  shell: bash -c "find . -name '*.deb' -print0"
    chdir={{repo_sources_path}}
  register: deb_paths

- name: Set variable to workaround ansible type evaluation issue
  set_fact:
    deb_paths_stdout_lines: "{{deb_paths.stdout_lines}}"

- name: Cleanup names
  shell: bash -c "find . -name '*.deb' -print0  | xargs -0 -I {} dpkg --info  {} | sed -n -e 's/^\s*Package:\s*//p'"
    chdir={{repo_sources_path}}
  register: installed_packages_names

- name: Set variable to workaround ansible type evaluation issue
  set_fact:
    installed_packages_names_stdout_lines: "{{installed_packages_names.stdout_lines}}"

- name: Send files to aptly repository
  shell: curl -X POST -F file=@{{ item.0 }} http://10.10.10.62:8080/api/files/{{ item.1 }}
  with_together:
    - "{{ installed_packages_names_stdout_lines|default([]) }}"
    - "{{ deb_paths_stdout_lines|default([]) }}"
