---
# Playbook for uploading deb files to an apt repo

- name: List all present deb packages
  shell: bash -c "ls *.deb"
    chdir={{repo_sources_path}}

- name: Save deb paths
  shell: echo {{item}}
    chdir={{repo_sources_path}}
  with_fileglob:
    - "{{repo_sources_path}}/*.deb"
  register: deb_paths

- name: Cleanup deb name first_path
  shell: bash -c "dpkg --info {{item}} | grep Package
  with_items:
    - "{{ deb_paths }}"
  register: deb_names_first_path

- name: Finish deb name cleanup
  replace: {{ item.replace('Package: ', '')}}
  with_items:
    - "{{ deb_names_first_path }}"
  register: deb_names
