---
# Playbook for uploading deb files to an apt repo

- name: List all present deb packages
  shell: bash -c "ls *.deb"
    chdir={{repo_sources_path}}

- name: Save deb paths
  shell: echo {{item}}
    chdir={{repo_sources_path}}
  with_fileglob:
    - "{{repo_sources_path}}/*.deb"
  register: deb_paths

- name: Cleanup deb name first_path
  shell: "dpkg --info {{item.results.stdout}} | grep 'Package: '"
  with_items:
    - "{{ deb_paths }}"
  register: deb_names_first_path

- name: Finish deb name cleanup
  shell: echo {{ item.results.stdout.replace('Package ', '')}}
  with_items:
    - "{{ deb_names_first_path }}"
  register: deb_names

- name: Send files to aptly repository
  shell: curl -X POST -F file=@{{ item.0.results.stdout }} http://10.10.10.62:8080/api/files/{{ item.1.results.stdout }}
  with_together:
    - "{{ deb_paths }}"
    - "{{ deb_names }}"
