ros_user: 'ros'
ros_user_comment: 'ROS'
ros_user_password: 'ros'
ros_user_autologin: True
ros_user_email: 'ros@example.com'
ros_user_background: ''
background_destination_folder: '/usr/share/shadowrobot/images/'
monospace_font: ''
