---

# The base image has an extra Ubuntu user we don't want
- name: Remove Ubuntu user
  user: name=ubuntu state=absent remove=yes

#
# Do some cleanup, we want the image as small as possible.
#
- name: apt autoclean
  command: apt-get autoclean

- name: apt clean
  command: apt-get clean

# This is probably bad for ROS
#- name: apt autoremove
#  command: apt-get autoremove --yes
