---
# Playbook for check cache

- name: check if special folder present
  stat: path={{special_cache_folder}}
  register: cache_folder_status

- name: Set flag build_was_cached
  set_fact:
    build_was_cached: yes
  when: cache_folder_status.stat.exists

- name: Set flag upgrade_all_packages
  set_fact:
    upgrade_all_packages: yes
  when: cache_folder_status.stat.exists

- name: Create special cache folder to help detected cached image {{special_cache_folder}}
  file: state=directory path={{special_cache_folder}}
  when: not cache_folder_status.stat.exists
