---
# Playbook for Deb files check

- name: check if project_sources_path variable was set
  fail: msg="Variable project_sources_path was not set"
  when: project_sources_path is not defined

- name: Read all packages paths in project
  shell: find -type f -name package.xml -printf "%h\n" chdir={{project_sources_path}}
  register: package_paths_list

- name: Set variable to workaround ansible type evaluation issue
  set_fact:
    package_paths_list_stdout_lines: "{{package_paths_list.stdout_lines}}"

- name: Clean debian packages folders in case of the cached build
  shell: bash -c "rm -rf ./debian && rm -rf ./obj-x86_64-linux-gnu"
    chdir={{project_sources_path}}/{{item}}
  with_items: "{{package_paths_list_stdout_lines|default([])}}"
  ignore_errors: True

- name: Clean debian packages from project directory
  shell: bash -c "find . -name '*.deb' -type f -delete"
    chdir={{project_sources_path}}
  ignore_errors: True

- name: Create debian package for every project package
  shell: bash -c "source /opt/ros/{{ros_release}}/setup.bash && bloom-generate rosdebian --os-name ubuntu --os-version trusty --ros-distro {{ros_release}} && fakeroot debian/rules binary"
    chdir={{project_sources_path}}/{{item}}
  with_items: "{{package_paths_list_stdout_lines|default([])}}"

- name: Install deb packages
  shell: bash -c "source /opt/ros/{{ros_release}}/setup.bash && sudo dpkg -R --install ."
    chdir={{project_sources_path}}
