---
# Playbook for Local CI init specific code

- name: check if local_repo_dir variable was set by build server
  fail: msg="Variable local_repo_dir was not set by CI server"
  when: local_repo_dir is not defined

- name: Include variables initializator
  include: roles/ci/servers/common/init/tasks/setup.yml
  vars:
      server_ros_workspace: "{{ansible_env.HOME}}/workspace"
      server_repo_sources_path: "{{ansible_env.HOME}}/workspace/src/{{local_repo_dir}}"
      server_is_pull_request: "{{ circle_is_pull_request is defined and circle_is_pull_request != '' }}"
      server_test_results_dir: "{{local_test_dir}}"
      server_code_coverage_results_dir: "{{local_code_coverage_dir}}"

- name: Copy source code from the repository into Docker container
  include: roles/ci/servers/common/init/tasks/copy_source.yml
  vars:
      server_repo_dir: "{{local_repo_dir}}"
