---

#- name: Install pycurl
#  apt: name=python-pycurl state=present

#- name: Add PyCharm ppa
#  apt_repository: repo='ppa:ubuntu-desktop/ubuntu-make'

#- name: Update package lists
#  apt: update_cache=yes

#- name: Install ubuntu make
#  apt: name=ubuntu-make state=present

- name: Create ros group variable(DEBUG)
  set_fact: 
    ros_group: ros

- name: Create pycharm directory
  sudo: yes
  file: path=/usr/share/umake/ide/pycharm state=directory mode=0777

- name: Install programming tools
  sudo: yes
  shell: bash -c "yes | umake ide pycharm /usr/share/umake/ide/pycharm"

- name: Change pycharm app location
  sudo: yes
  command: cp ~{{ros_user}}/.local/share/applications/jetbrains-pycharm-ce.desktop /usr/share/applications

- name: Set workspace for pycharm icon
  lineinfile: dest=/usr/share/applications/jetbrains-pycharm-ce.desktop regexp=^Exec= line="Exec="/usr/share/umake/ide/pycharm/bin/pycharm.sh" %F"

- name: Set favorite icons
  shell: dbus-launch --exit-with-session gsettings set com.canonical.Unity.Launcher favorites "['application://ubiquity.desktop', 'application://jetbrains-pycharm-ce.desktop', 'application://terminator.desktop', 'application://nautilus.desktop', 'application://firefox.desktop', 'unity://running-apps', 'unity://expo-icon', 'unity://devices']"
  sudo_user: "{{ros_user}}"