---

- name: Add PyCharm ppa
  apt_repository: repo='ppa:mystic-mirage/pycharm'

- name: Update package lists
  apt: update_cache=yes

- name: Install programming tools
  apt: name={{item}}
  with_items:
    - pycharm-community

- name: Set workspace for pycharm icon
  lineinfile: dest=/usr/share/applications/pycharm-community.desktop regexp=^Exec= line="Exec=bash -i -c \"pycharm-community\" %F"