---
# Installs the ubuntu dekstop system.
# Useful for adding the GUI to base images.
# Use ubuntu_desktop_thin: true to install a more minimal system.

- name: Update package lists
  apt: update_cache=yes

- name: Install Ubuntu desktop
  apt: name={{item}}
  with_items:
    - ubuntu-desktop
  register: install_desktop_result
  when: not ubuntu_desktop_thin

- name: Thin desktop
  apt: name={{item}} state=absent purge=yes
  with_items:
    - libreoffice
    - libreoffice-math
    - libreoffice-draw
    - libreoffice-writer
    - libreoffice-impress
    - libreoffice-calc
    - libreoffice-base
    - thunderbird
    - shotwell
    - rhythmbox
  when: ubuntu_desktop_thin

#
# Reboot if we installed a desktop
#

# This wont work when running under vagrant as you need to vagrant up to get
# networking setup properly.
- name: Restart machine
  command: shutdown -r now "Ansible updates triggered"
  async: 0
  poll: 0
  ignore_errors: true
  when: install_desktop_result.changed and ansible_user_id != 'vagrant' and ansible_env.SUDO_USER != 'vagrant'

- name: Reload vagrant
  local_action: command vagrant reload {{ inventory_hostname }} chdir={{ vagrant_dir }}
  async: 0
  poll: 0
  #ignore_errors: true
  sudo: no
  when: install_desktop_result.changed and (ansible_user_id=='vagrant' or ansible_env.SUDO_USER=='vagrant')

# Wait for a normal reboot to go down.
# No wait for down on vagrant as the reload command blocks.
- name: Wait for machine to go down
  local_action: wait_for host={{ ansible_ssh_host }} port={{ ansible_ssh_port | default(22) }} state=stopped
  sudo: false
  when: install_desktop_result.changed and ansible_user_id != 'vagrant' and ansible_env.SUDO_USER != 'vagrant'

- name: Wait for machine to come back
  local_action: wait_for host={{ ansible_ssh_host }} port={{ ansible_ssh_port | default(22) }} state=started
  sudo: false
  when: install_desktop_result.changed

#
# Do some cleanup, we want the image as small as possible.
#
- name: apt autoclean
  command: apt-get autoclean

- name: apt clean
  command: apt-get clean

# This is probably bad for ROS
#- name: apt autoremove
#  command: apt-get autoremove --yes
