---
# Playbook Continuous Integration servers.

- hosts: all
  vars:
    ros_release: "indigo"
    skip_build: no
  roles:
    - {role: ci/servers/shippable/init, tags: ["shippable","shippable_init"]}
    - {role: ci/build_pr_only, tags: ["build_pr_only"]}
    - {role: ci/install, when: skip_build == no, tags: ["install"]}
    - {role: ci/create_workspace, when: skip_build == no, tags: ["create_workspace"]}
    - {role: ci/update_dependencies, when: skip_build == no, tags: ["update_dependencies"]}
    - {role: ci/build, when: skip_build == no, tags: ["build"]}
    - {role: ci/unit_tests, when: skip_build == no, tags: ["unit_tests"]}
    - {role: ci/servers/shippable/finalize, when: skip_build == no, tags: ["shippable","shippable_finalize"]}
