---
# Playbook Continuous Integration servers.

- hosts: all
  vars:
    ros_release: "indigo"
  roles:
    - {role: ci/servers/shippable/init, tags: ["shippable"]}
    - {role: ci/servers/semaphore/init, tags: ["semaphore"]}
    - {role: ci/servers/circle/init, tags: ["circle"]}
    - {role: ci/servers/docker_hub/init, tags: ["docker_hub"]}
    - {role: ci/build/pr_only, tags: ["build_pr_only"]}
    - {role: ci/init/check_cache, when: run_build, tags: ["check_cache"]}
    - {role: ci/init/install, when: run_install, tags: ["install"]}
    - {role: ci/init/create_workspace, when: run_install, tags: ["create_workspace"]}
    - {role: ci/update_dependencies, when: run_build, tags: ["update_dependencies", "build", "unit_tests",
                                                             "code_coverage", "codecov_tool", "python_code_coverage",
                                                             "cpp_code_coverage", "check_deb"]}
    - {role: ci/build/catkin, when: run_build, tags: ["build", "unit_tests", "code_coverage", "codecov_tool",
                                                      "python_code_coverage", "cpp_code_coverage"]}
    - {role: ci/code_coverage/python/setup, when: run_build, tags: ["python_code_coverage", "code_coverage", "codecov_tool"]}
    - {role: ci/code_coverage/cpp/setup, when: run_build, tags: ["cpp_code_coverage", "code_coverage", "codecov_tool"]}
    - {role: ci/unit_tests, when: run_build, tags: ["unit_tests", "code_coverage", "codecov_tool",
                                                    "python_code_coverage", "cpp_code_coverage"]}
    - {role: ci/code_style_check/python, when: run_build, tags: ["python_code_style_check", "code_style_check"]}
    - {role: ci/code_style_check/cpp, when: run_build, tags: ["cpp_code_style_check", "code_style_check"]}
    - {role: ci/deploy/check_deb, when: run_build, tags: ["check_deb"]}
    - {role: ci/servers/shippable/finalize, when: run_build, tags: ["shippable"]}
    - {role: ci/servers/circle/finalize, when: run_build, tags: ["circle"]}
    - {role: ci/servers/semaphore/finalize, when: run_build, tags: ["semaphore"]}
    - {role: ci/code_coverage/python/finalize, when: run_build, tags: ["python_code_coverage", "code_coverage", "codecov_tool"]}
    - {role: ci/code_coverage/cpp/finalize, when: run_build, tags: ["cpp_code_coverage", "code_coverage", "codecov_tool"]}
    - {role: ci/code_coverage/codecov, when: run_build, tags: ["codecov_tool"]}
