---
# Playbook Continuous Integration servers.

- hosts: all
  vars:
    ros_release: 'indigo'
  sudo: yes
  roles:
    - {role: ros_install, tags: ['ros_install']}
    - {role: ros_workspace, tags: ['ros_workspace']}
