---
# Playbook Continuous Integration servers.

- hosts: all
  vars:
    ros_release: "indigo"
  roles:
    - {role: ci/servers/shippable/init, tags: ["shippable","shippable_init"]}
    - {role: ci/install, tags: ["install"]}
    - {role: ci/create_workspace, tags: ["create_workspace"]}
    - {role: ci/update_dependencies, tags: ["update_dependencies"]}
    - {role: ci/build, tags: ["build"]}
    - {role: ci/unit_tests, tags: ["unit_tests"]}
    - {role: ci/servers/shippable/finalize, tags: ["shippable","shippable_finalize"]}
