---
# Playbook Continuous Integration servers.

- hosts: all
  vars:
    ros_release: "indigo"
  roles:
    - {role: ci/servers/shippable/init, tags: ["shippable","shippable_init"]}
    - {role: ci/build/pr_only, tags: ["build_pr_only"]}
    - {role: ci/init/install, when: run_build, tags: ["install"]}
    - {role: ci/init/create_workspace, when: run_build, tags: ["create_workspace"]}
    - {role: ci/update_dependencies, when: run_build, tags: ["update_dependencies", "build", "unit_tests", "python_code_style_check", "cpp_code_style_check", "code_style_check", "code_coverage", "codecov_tool"]}
    - {role: ci/build/catkin, when: run_build, tags: ["build", "unit_tests", "python_code_style_check", "cpp_code_style_check", "code_style_check", "code_coverage", "codecov_tool"]}
    - {role: ci/code_style_check/python, when: run_build, tags: ["python_code_style_check", "code_style_check"]}
    - {role: ci/code_style_check/cpp, when: run_build, tags: ["cpp_code_style_check", "code_style_check"]}
    - {role: ci/code_coverage/data, when: run_build, tags: ["code_coverage", "codecov_tool"]}
    - {role: ci/unit_tests, when: run_build, tags: ["unit_tests", "python_code_style_check", "cpp_code_style_check", "code_style_check", "code_coverage", "codecov_tool"]}
    - {role: ci/servers/shippable/finalize, when: run_build, tags: ["shippable","shippable_finalize"]}
    - {role: ci/code_coverage/codecov, when: run_build, tags: ["codecov_tool"]}
