---
# Playbook Continuous Integration servers.

- hosts: all
  vars:
    ros_release: 'indigo'
  sudo: yes
  roles:
    - {name: ros_install, tags: ros_install}
    - {name: ros_workspace, tags: ros_workspace}
