---
- hosts: default
  vars:
    ros_release: 'hydro'
    ros_user: 'hand'
    ros_user_comment: 'Shadow Hand'
    ros_user_password: 'hand'
    ros_user_email: 'software@shadowrobot.com'
    ros_workspace: "~{{ros_user}}/{{ros_release}}_ws"
    ros_workspace_install: "../data/shadow_robot-{{ros_release}}.rosinstall"
  #remote_user: root
  sudo: yes
  roles:
  - ros_machine
  - ros_user
  - ros_workspace
  tasks:

  # Note: Handlers only fire after all the taks. Once for however many notifies
  #    notify:
  #    - restart ntpd
  handlers:
  #  - name: restart ntpd
  #    service: name=ntpd state=restarted

