---
- hosts: all
  vars:
    # Where to find the build tools. Mounted by vagrant
    sr_build_tools: /opt/shadow/sr-build-tools
    ros_release: 'hydro'
    ros_user: 'hand'
    ros_user_password: 'hand'
    ros_user_email: 'software@shadowrobot.com'
    ros_workspace: "~{{ros_user}}/{{ros_release}}_ws"
    ros_workspace_install: "{{sr_build_tools}}/data/shadow_robot-{{ros_release}}.rosinstall"
    desktop_files: "{{sr_build_tools}}/"
  #remote_user: root
  sudo: yes
  roles:
  - ros_machine
  tasks:
    # Install packages for the hand machine
    - name: Install packages
      apt: name={{item}}
      with_items:
        - git
        - vim
        - emacs
        - tree
        - htop

    # User setup
    - name: Add ros group
      group: name=ros

    - name: Add {{ros_user}} user
      user: name={{ros_user}}
        comment="Shadow Hand"
        shell=/bin/bash
        append=yes groups=ros,adm,sudo,plugdev,cdrom
    - name: Set users password
      shell: "echo '{{ros_user}}:{{ros_user_password}}' | chpasswd"

    - name: Give user passwordless sudo.
      lineinfile: "dest=/etc/sudoers state=present regexp='^{{ros_user}}' line='{{ros_user}}  ALL=(ALL) NOPASSWD:  ALL' insertafter=EOF"

    - name: Setup git name
      command: git config --global user.name "{{ros_user}}"
    - name: Setup git email
      command: git config --global user.email "{{ros_user_email}}"

    - name: Update rosdep
      shell: bash -c "source /opt/ros/{{ros_release}}/setup.bash && rosdep update"
      sudo: yes
      sudo_user: "{{ros_user}}"

    # Desktop
    - name: Install home directory files
      copy: src=files/home/{{ros_user}}/ dest=\~{{ros_user}}/ owner={{ros_user}} group=ros

    # Workspace
    - name: Create workspace dir {{ros_workspace}}
      file: state=directory path={{ros_workspace}}/src owner={{ros_user}} group=ros
      sudo: yes
      sudo_user: "{{ros_user}}"

    - name: Init workspace
      command: wstool init .
        chdir={{ros_workspace}}/src
        creates={{ros_workspace}}/src/.rosinstall
      sudo: yes
      sudo_user: "{{ros_user}}"

    - name: catkin_init_workspace
      shell: bash -c "source /opt/ros/{{ros_release}}/setup.bash && catkin_init_workspace"
        chdir={{ros_workspace}}/src
        creates={{ros_workspace}}/src/CMakeLists.txt
      sudo: yes
      sudo_user: "{{ros_user}}"

    # Do an initial make of the empty workspace to get a setup.bash.
    # If there is one already don't do this, so we don't trigger a big make
    - name: catkin make workspace
      shell: bash -c "source /opt/ros/{{ros_release}}/setup.bash && catkin_make"
        chdir={{ros_workspace}}
        creates={{ros_workspace}}/devel/setup.bash
      sudo: yes
      sudo_user: "{{ros_user}}"

    - name: Update users basrc to point to the workspace
      lineinfile: dest=\~{{ros_user}}/.bashrc
                  line="source {{ros_workspace}}/devel/setup.bash"
                  regexp='^source.*/setup\.bash'
                  insertafter=EOF
                  backup=yes

    # Install the shadow code
    - name: Install {{ros_workspace_install}}
      shell: bash -c "{{item}}" chdir={{ros_workspace}}/src
      sudo: yes
      sudo_user: "{{ros_user}}"
      with_items:
        - wstool merge -y "{{ros_workspace_install}}"
        - wstool update

    - name: Install dependancies
      shell: bash -c "source {{ros_workspace}}/devel/setup.bash && rosdep install --default-yes --all --ignore-src"
             chdir={{ros_workspace}}
      sudo: yes
      sudo_user: "{{ros_user}}"

    - name: catkin_make
      shell: bash -c "source {{ros_workspace}}/devel/setup.bash && catkin_make"
        chdir={{ros_workspace}}
      sudo: yes
      sudo_user: "{{ros_user}}"

  # Note: Handlers only fire after all the taks. Once for however many notifies
  #    notify:
  #    - restart ntpd
  handlers:
  #  - name: restart ntpd
  #    service: name=ntpd state=restarted

