---
- hosts: default
  vars:
    ros_release: 'hydro'
    ros_user: 'ros'
    ros_user_comment: 'ROS'
    ros_user_password: 'ros'
    ros_user_email: 'ros@example.com'
  sudo: yes
  roles:
  # Allow the mchine to have latest guest additions installed by mounting the
  # CD image inside the machine. Without this trying to install the latest
  # additions breaks the vagrant setup.
  - dkms
  - ros_machine
  - ros_user

