---
# Playbook for all the Vagrant machines.

- hosts: ros-hydro-desktop-precise64
  vars:
    ros_release: 'hydro'
    ros_user: 'ros'
    ros_user_comment: 'ROS'
    ros_user_password: 'ros'
    ros_user_email: 'ros@example.com'
  sudo: yes
  roles:
  # Allow the mchine to have latest guest additions installed by mounting the
  # CD image inside the machine. Without this trying to install the latest
  # additions breaks the vagrant setup.
  - dkms
  - ros_machine
  - ros_user

- hosts: hand-hydro-precise64
  vars:
    ros_release: 'hydro'
    ros_user: 'hand'
    ros_user_comment: 'Shadow Hand'
    ros_user_password: 'hand'
    ros_user_email: 'software@shadowrobot.com'
    ros_workspace: "~{{ros_user}}/{{ros_release}}_ws"
    ros_workspace_install: "../data/shadow_robot-{{ros_release}}.rosinstall"
  sudo: yes
  roles:
  - ros_machine
  - ros_user
  - ros_workspace
