---
# Playbook for all the Vagrant machines.

- hosts: ros-hydro-desktop-precise64
  vars:
    ros_release: 'hydro'
    ubuntu_desktop_thin: true
  sudo: yes
  roles:
  - ubuntu_desktop
  # dkms - Allow the machine to have latest guest additions installed by
  # mounting the CD image inside the machine. Without this trying to install
  # the latest additions breaks the vagrant setup.
  - dkms
  - ros_install
  - ros_user

- hosts: ros-indigo-desktop-trusty64
  vars:
    ros_release: 'indigo'
    ubuntu_desktop_thin: true
  sudo: yes
  roles:
  - ubuntu_desktop
  - dkms
  - ros_install
  - ros_user

- hosts: hand-prod
  vars:
    ros_release: 'hydro'
    ros_user: 'hand'
    ros_user_comment: 'Shadow Hand'
    ros_user_password: 'hand'
    ros_user_email: 'software@shadowrobot.com'
    ros_user_home_files: files/home/hand_prod/
    ros_workspace_install: "../data/shadow_robot-{{ros_release}}.rosinstall"
  sudo: yes
  roles:
  - ros_install
  - ros_user
  - ros_workspace

- hosts: hand
  vars:
    ros_release: 'hydro'
    ros_user: 'hand'
    ros_user_comment: 'Shadow Hand'
    ros_user_password: "password"
    ros_user_email: 'software@shadowrobot.com'
    ros_workspace_install: "../data/shadow_robot-{{ros_release}}.rosinstall"
    ros_user_background: "ShadowRobot-smaller.jpg_1280x1280.jpg"
    monospace_font: "Ubuntu Mono 11"
    ros_packages:
      - shadow-robot
      - shadow-robot-ethercat
      - sr-config
      - sr-visualization
  sudo: yes
  roles:
  - ros_install
  - ros_user

#development version of the hand machine
- hosts: hand-dev
  vars:
    ros_release: 'hydro'
    ros_user: 'hand'
    ros_user_comment: 'Shadow Hand'
    ros_user_password: "password"
    ros_user_email: 'software@shadowrobot.com'
    ros_workspace_install: "../data/shadow_robot-{{ros_release}}.rosinstall"
    ros_user_background: "ShadowRobot-smaller.jpg_1280x1280.jpg"
    monospace_font: "Ubuntu Mono 11"
  sudo: yes
  roles:
  - ros_install
  - ros_user
  - ros_workspace
  - share_folder

- hosts: ronex
  vars:
    ros_release: 'hydro'
    ros_user: 'ronex'
    ros_user_comment: 'RoNeX'
    ros_user_password: "password"
    ros_user_email: 'software@shadowrobot.com'
    ros_user_background: "ronex.jpg"
    monospace_font: "Ubuntu Mono 11"
    ros_packages:
      - sr-ronex

  sudo: yes
  roles:
  - ronex_user

- hosts: glassbot
  sudo: yes
  vars:
    ros_packages:
      - rosbridge-suite
      - tf2-web-republisher
  pre_tasks:
    # To install a private repo need to pass the auth sock (ssh agent
    # forwarding onto root (wont work for other users due to perms on the
    # socket, which is good)
    - name: Pass SSH_AUTH_SOCK through sudo
      lineinfile: dest=/etc/sudoers
                 state=present
                 insertbefore='^Defaults\s+env_reset'
                 line='Defaults        env_keep+=SSH_AUTH_SOCK'
                 validate='visudo -cf %s'
                 backup=yes
  roles:
    - glassbot
    - webserver
