---
# Playbook for all the Vagrant machines.

- hosts: ros-hydro-desktop-precise64
  vars:
    ros_release: 'hydro'
    ubuntu_desktop_thin: true
  sudo: yes
  roles:
  - ubuntu_desktop
  # dkms - Allow the machine to have latest guest additions installed by
  # mounting the CD image inside the machine. Without this trying to install
  # the latest additions breaks the vagrant setup.
  - dkms
  - ros_install
  - ros_user

- hosts: hand-hydro-precise64
  vars:
    ros_release: 'hydro'
    ros_user: 'hand'
    ros_user_comment: 'Shadow Hand'
    ros_user_password: 'hand'
    ros_user_email: 'software@shadowrobot.com'
    ros_workspace_install: "../data/shadow_robot-{{ros_release}}.rosinstall"
  sudo: yes
  roles:
  - ros_install
  - ros_user
  - ros_workspace

- hosts: jenkins-slave
  vars:
    ros_release: 'hydro'
    jenkins_user: 'jenkins'
    jenkins_user_comment: 'Jenkins Slave User'
    jenkins_user_email: 'software@shadowrobot.com'
    jenkins_url: jenkins:8080
    sr_build_tools_dir: "/opt/shadow/sr-build-tools"
  sudo: yes
  roles:
  - ros_install
  - jenkins_slave
