---
# Playbook for Python code style check

- name: Read all packages paths in workspace
  shell: find -type f -name package.xml -printf "%h\n" chdir={{ros_workspace}}
  register: package_paths_list

- name: Find Python files in each package
  shell: find -type f -name "*.py" -printf "%p "
    chdir={{ros_workspace}}/{{item}}
  with_items: "{{package_paths_list.stdout_lines}}"
  register: package_paths_and_python_files

- name: Execute roslint for every package and write results in unit tests format
  shell: rosrun roslint test_wrapper {{ros_workspace}}/build/test_results/{{item.item|basename}}/roslint-python-{{item.item|basename}}.xml "rosrun roslint pep8 {{item.stdout}}"
    chdir={{ros_workspace}}/{{item.item}}
  with_items: "{{package_paths_and_python_files.results}}"
  when: item.stdout != ""
  ignore_errors: True
