---
# Playbook for codecov

- name: check if codecov_secure variable was set
  fail: msg="Variable codecov_secure was not set"
  when: codecov_secure is not defined

- name: Send data to codecov
  command: bash <(curl -s https://codecov.io/bash)
  environment:
        secure: "{{codecov_secure}}"
