# Install packages a jenkins user will need
- name: Install packages
  apt: name={{item}}
  with_items:
    - ntp
    - acpid
    - git
    - ssh
    - openjdk-6-jre # to run the jenkins slave agent
    - python-yaml

- name: Add {{jenkins_user}} user
  user: name={{jenkins_user}}
    comment="{{jenkins_user_comment}}"
    append=yes groups=adm,sudo,plugdev,cdrom

- name: Give user passwordless sudo
  lineinfile: "dest=/etc/sudoers state=present regexp='^{{jenkins_user}}' line='{{jenkins_user}}  ALL=(ALL) NOPASSWD:  ALL' insertafter=EOF"

- name: Test for server pub key
  command: 'wget -O /tmp/ansible_jenkins_server_key "{{jenkins_server_pubkey}}"'

- name: Debug content
  debug: msg="File={{ lookup('pipe', 'cat /tmp/ansible_jenkins_server_key') }}"

