# Install packages a jenkins user will need
- name: Install packages
  apt: name={{item}}
  with_items:
    - ntp
    - acpid
    - git
    - ssh
    - openjdk-6-jre # to run the jenkins slave agent
    - python-yaml

- name: Add {{jenkins_user}} user
  user: name={{jenkins_user}}
    comment="{{jenkins_user_comment}}"
    append=yes groups=adm,sudo,plugdev,cdrom

- name: Give user passwordless sudo
  lineinfile: "dest=/etc/sudoers state=present regexp='^{{jenkins_user}}' line='{{jenkins_user}}  ALL=(ALL) NOPASSWD:  ALL' insertafter=EOF"

- name: Get Jenkins server pub key
  get_url: url="{{jenkins_server_pubkey}}" dest=/tmp/ansible_jenkins_server_key

- name: Read key
  command: cat /tmp/ansible_jenkins_server_key
  register: cat_result

- name: Install key
  authorized_key: user="{{jenkins_user}}" key="{{cat_result.stdout}}"

