---
# Playbook for unit tests

- name: check if code_coverage_options variable was set
  fail: msg="Variable code_coverage_options was not set"
  when: code_coverage_options is not defined

- name: catkin run tests
  shell: bash -c 'source {{ros_workspace}}/devel/setup.bash && catkin_make run_tests -DCATKIN_BLACKLIST_PACKAGES="{{ non_repo_packages }}" '
    chdir={{ros_workspace}}
  when: code_coverage_options == ""

- name: catkin run tests with code coverage
  shell: bash -c 'source {{ros_workspace}}/devel/setup.bash && {{python_code_coverage_options}} catkin_make run_tests -DCATKIN_BLACKLIST_PACKAGES="{{ non_repo_packages }}" -DCMAKE_CXX_FLAGS="{{code_coverage_options}}" '
    chdir={{ros_workspace}}
  when: code_coverage_options != ""
