---
# Playbook for unit tests

- name: check if generate_code_coverage variable was set
  fail: msg="Variable generate_code_coverage was not set"
  when: generate_code_coverage is not defined

- name: catkin run tests
  shell: bash -c "source {{ros_workspace}}/devel/setup.bash && catkin_make run_tests -DSR_COMMON_CODE_COVERAGE={{generate_code_coverage}} "
    chdir={{ros_workspace}}
